min_units: 5
min_behav_trials: 10
n_bins: 3
single_cell_filter: True
mi_filter: True
decoder_filter: False
discretize: 1
repeats_for_bias_correction: 5
bias_correction: "qe"
min_rt: 0.08
max_rt: None
hemisphere: ("left", "right")
frames: [0,2]
freeze: None
pq_location: "/usr/people/kundu/code/ibl-partial-info-decomp/data/external/stimside_stage2.pqt"
stim_prior_regions : [
        "VISp",
        "MOs",
        "SSp-ul",
        "ACAd",
        "PL",
        "CP",
        "VPM",
        "MG",
        "LGd",
        "ZI",
        "SNr",
        "MRN",
        "SCm",
        "PAG",
        "APN",
        "RN",
        "PPN",
        "PRNc",
        "PRNr",
        "GRN",
        "IRN",
        "PGRN",
        "CUL4 5",
        "SIM",
        "IP",
    ]
region_defaults: {
  'widefield': [
    [ "ACAd" ],
    [ "AUDd" ],
    [ "AUDp" ],
    [ "AUDpo" ],
    [ "AUDv" ],
    [ "FRP" ],
    [ "MOB" ],
    [ "MOp" ],
    [ "MOs" ],
    [ "PL" ],
    [ "RSPagl" ],
    [ "RSPd" ],
    [ "RSPv" ],
    [ "SSp-bfd" ],
    [ "SSp-ll" ],
    [ "SSp-m" ],
    [ "SSp-n" ],
    [ "SSp-tr" ],
    [ "SSp-ul" ],
    [ "SSp-un" ],
    [ "SSs" ],
    [ "TEa" ],
    [ "VISa" ],
    [ "VISal" ],
    [ "VISam" ],
    [ "VISl" ],
    [ "VISli" ],
    [ "VISp" ],
    [ "VISpl" ],
    [ "VISpm" ],
    [ "VISpor" ],
    [ "VISrl" ],
  ]}
